export const PROJECTS = {
  CLEVER PARK: {
    images: [
      "/assets/Projects/Clever Park/1.webp",
      "/assets/Projects/Clever Park/2.webp",
      "/assets/Projects/Clever Park/3.webp",
      "/assets/Projects/Clever Park/4.webp",
      "/assets/Projects/Clever Park/5.webp",
      "/assets/Projects/Clever Park/6.webp",
      "/assets/Projects/Clever Park/7.webp",
      "/assets/Projects/Clever Park/8.webp",
      "/assets/Projects/Clever Park/9.webp",
      "/assets/Projects/Clever Park/10.webp",
      "/assets/Projects/Clever Park/11.webp",
      "/assets/Projects/Clever Park/12.webp",
      "/assets/Projects/Clever Park/13.webp",
      "/assets/Projects/Clever Park/14.webp",
      "/assets/Projects/Clever Park/15.webp",
      "/assets/Projects/Clever Park/16.webp",
      "/assets/Projects/Clever Park/17.webp",
    ],
    constant: "/assets/images/project1/constant-image.png",
  },
  MEDI TRIBE: {
    images: [
      "/assets/images/project1/1.png",
      "/assets/images/project1/2.jpg",
      "/assets/images/project1/3.jpg",
      "/assets/images/project1/4.jpg",
      "/assets/images/project1/5.jpg",
      "/assets/images/project1/6.jpg",
      "/assets/images/project1/7.jpg",
    ],
    constant: "/assets/images/project1/constant-image.png",
  },
  project3: {
    images: [
      "/assets/images/project1/1.png",
      "/assets/images/project1/2.jpg",
      "/assets/images/project1/3.jpg",
      "/assets/images/project1/4.jpg",
      "/assets/images/project1/5.jpg",
      "/assets/images/project1/6.jpg",
      "/assets/images/project1/7.jpg",
    ],
    constant: "/assets/images/project1/constant-image.png",
  },